replicaCount: 2

image:
  repository: 831926627653.dkr.ecr.eu-west-3.amazonaws.com/leumi/app:1.0

service:
  type: ClusterIP
  port: 443
  targetPort: 5000


secret:
  name: api-key-secret
  data:
    API_KEY: U1VXSzlFVDhNRk5FQ1hZM1NDTlFLNDY0SA==
