pipeline {
    agent any 
    stages {
        stage('test stage') {
            steps {
                sh "pwd"
                sh "ls"
                sh "echo "hello world!""
            }
        }
    }

}